export const ALL_PERMISSIONS = [
  "users.view",
  "users.create",
  "users.edit",
  "users.delete",
  "users.ban",
  "users.unban",
  "users.view_email",
  "users.change_role",
  "users.assign_custom_role",
  "users.view_profile",
  "players.view",
  "players.create",
  "players.edit",
  "players.delete",
  "players.reset_stats",
  "players.edit_elo",
  "players.edit_tier",
  "players.edit_wins",
  "players.edit_losses",
  "players.edit_streak",
  "players.view_stats",
  "matches.view",
  "matches.create",
  "matches.delete",
  "matches.edit",
  "matches.approve",
  "matches.reject",
  "submissions.view",
  "submissions.create",
  "submissions.approve",
  "submissions.reject",
  "submissions.delete",
  "submissions.view_evidence",
  "tickets.view",
  "tickets.create",
  "tickets.reply",
  "tickets.close",
  "tickets.delete",
  "tickets.reassign",
  "tickets.view_private",
  "announcements.view",
  "announcements.create",
  "announcements.edit",
  "announcements.delete",
  "announcements.pin",
  "announcements.publish",
  "seasons.view",
  "seasons.create",
  "seasons.edit",
  "seasons.delete",
  "seasons.reset",
  "seasons.end",
  "roles.view",
  "roles.create",
  "roles.edit",
  "roles.delete",
  "roles.assign",
  "roles.revoke",
  "roles.edit_permissions",
  "settings.view",
  "settings.edit_general",
  "settings.edit_homepage",
  "settings.edit_server_ip",
  "settings.edit_discord",
  "settings.edit_leaderboard",
  "settings.edit_theme",
  "settings.edit_social",
  "admin.access",
  "admin.view_analytics",
  "admin.view_logs",
  "admin.delete_logs",
  "admin.manage_bans",
  "admin.export_data",
  "mod.mute",
  "mod.kick",
  "mod.warn",
  "mod.view_reports",
  "mod.handle_reports",
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

export const PERMISSION_GROUPS = {
  "User Management": ALL_PERMISSIONS.filter(p => p.startsWith("users.")),
  "Player Management": ALL_PERMISSIONS.filter(p => p.startsWith("players.")),
  "Match Management": ALL_PERMISSIONS.filter(p => p.startsWith("matches.")),
  "Submission Management": ALL_PERMISSIONS.filter(p => p.startsWith("submissions.")),
  "Ticket Management": ALL_PERMISSIONS.filter(p => p.startsWith("tickets.")),
  "Announcements": ALL_PERMISSIONS.filter(p => p.startsWith("announcements.")),
  "Season Management": ALL_PERMISSIONS.filter(p => p.startsWith("seasons.")),
  "Role Management": ALL_PERMISSIONS.filter(p => p.startsWith("roles.")),
  "Site Settings": ALL_PERMISSIONS.filter(p => p.startsWith("settings.")),
  "Admin Panel": ALL_PERMISSIONS.filter(p => p.startsWith("admin.")),
  "Moderation": ALL_PERMISSIONS.filter(p => p.startsWith("mod.")),
};
